package com.example.slider;

import androidx.appcompat.app.AppCompatActivity;

import android.content.pm.ActivityInfo;
import android.os.Bundle;
import android.text.method.LinkMovementMethod;
import android.view.View;
import android.view.WindowManager;
import android.widget.TextView;

public class Surse extends AppCompatActivity {

    TextView scris1;
    TextView scris2;
    TextView scris3;
    TextView scris4;
    TextView scris5;
    TextView scris6;
    TextView scris7;
    TextView scris8;
    TextView scris9;
    TextView scris10;
    TextView scris11;
    TextView scris12;
    TextView scris13;
    TextView scris14;
    TextView scris15;
    TextView scris16;
    TextView scris17;
    TextView scris18;
    TextView scris19;
    TextView scris20;
    TextView scris21;
    TextView scris22;
    //TextView scris 23 nu are
    TextView scris24;
    TextView scris25;
    TextView scris26;
    TextView scris27;
    TextView scris28;
    TextView scris29;
    TextView scris30;
    TextView scris31;
    TextView scris32;
    TextView scris33;
    TextView scris34;
    TextView scris35;
    TextView scris36;
    TextView scris37;
    TextView scris38;
    TextView scris39;
    TextView scris40;
    TextView scris41;
    TextView scris42;
    TextView scris43;
    TextView scris44;
    TextView scris45;
    TextView scris46;
    TextView scris47;
    TextView scris48;
    TextView scris49;
    TextView scris50;
    TextView scris51;
    TextView scris52;
    TextView scris53;
    TextView scris54;
    TextView scris55;
    TextView scris56;
    TextView scris57;
    TextView scris58;
    TextView scris59;
    TextView scris60;
    TextView scris61;
    TextView scris62;
    TextView scris63;
    TextView scris64;
    TextView scris65;
    TextView scris66;
    TextView scris67;
    TextView scris68;
    TextView scris69;
    TextView scris70;
    TextView scris71;
    TextView scris72;
    TextView scris73;
    TextView scris74;
    TextView scris75;
    TextView scris76;
    TextView scris77;
    TextView scris78;
    TextView scris79;
    TextView scris80;
    TextView scris81;
    TextView scris82;
    TextView scris83;
    TextView scris84;
    TextView scris85;
    TextView scris86;
    TextView scris87;
    TextView scris88;
    TextView scris89;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);
        getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,WindowManager.LayoutParams.FLAG_FULLSCREEN);
        setContentView(R.layout.activity_surse);
        TextView scris1;
        scris1=(TextView) findViewById(R.id.link1);
        scris1.setMovementMethod(LinkMovementMethod.getInstance());
        scris2=(TextView) findViewById(R.id.link2);
        scris2.setMovementMethod(LinkMovementMethod.getInstance());
        scris3=(TextView) findViewById(R.id.link3);
        scris3.setMovementMethod(LinkMovementMethod.getInstance());
        scris4=(TextView) findViewById(R.id.link4);
        scris4.setMovementMethod(LinkMovementMethod.getInstance());
        scris5=(TextView) findViewById(R.id.link5);
        scris5.setMovementMethod(LinkMovementMethod.getInstance());
        scris6=(TextView) findViewById(R.id.link6);
        scris6.setMovementMethod(LinkMovementMethod.getInstance());
        scris7=(TextView) findViewById(R.id.link7);
        scris7.setMovementMethod(LinkMovementMethod.getInstance());
        scris8=(TextView) findViewById(R.id.link8);
        scris8.setMovementMethod(LinkMovementMethod.getInstance());
        scris9=(TextView) findViewById(R.id.link9);
        scris9.setMovementMethod(LinkMovementMethod.getInstance());
        scris10=(TextView) findViewById(R.id.link10);
        scris10.setMovementMethod(LinkMovementMethod.getInstance());
        scris11=(TextView) findViewById(R.id.link11);
        scris11.setMovementMethod(LinkMovementMethod.getInstance());
        scris12=(TextView) findViewById(R.id.link12);
        scris12.setMovementMethod(LinkMovementMethod.getInstance());
        scris13=(TextView) findViewById(R.id.link13);
        scris13.setMovementMethod(LinkMovementMethod.getInstance());
        scris14=(TextView) findViewById(R.id.link14);
        scris14.setMovementMethod(LinkMovementMethod.getInstance());
        scris15=(TextView) findViewById(R.id.link15);
        scris15.setMovementMethod(LinkMovementMethod.getInstance());
        scris16=(TextView) findViewById(R.id.link16);
        scris16.setMovementMethod(LinkMovementMethod.getInstance());
        scris17=(TextView) findViewById(R.id.link17);
        scris17.setMovementMethod(LinkMovementMethod.getInstance());
        scris18=(TextView) findViewById(R.id.link18);
        scris18.setMovementMethod(LinkMovementMethod.getInstance());
        scris19=(TextView) findViewById(R.id.link19);
        scris19.setMovementMethod(LinkMovementMethod.getInstance());
        scris20=(TextView) findViewById(R.id.link20);
        scris20.setMovementMethod(LinkMovementMethod.getInstance());
        scris21=(TextView) findViewById(R.id.link21);
        scris21.setMovementMethod(LinkMovementMethod.getInstance());
        scris22=(TextView) findViewById(R.id.link22);
        scris22.setMovementMethod(LinkMovementMethod.getInstance());
        //23
        //23
        scris24=(TextView) findViewById(R.id.link24);
        scris24.setMovementMethod(LinkMovementMethod.getInstance());
        scris25=(TextView) findViewById(R.id.link25);
        scris25.setMovementMethod(LinkMovementMethod.getInstance());
        scris26=(TextView) findViewById(R.id.link26);
        scris26.setMovementMethod(LinkMovementMethod.getInstance());
        scris27=(TextView) findViewById(R.id.link27);
        scris27.setMovementMethod(LinkMovementMethod.getInstance());
        scris28=(TextView) findViewById(R.id.link28);
        scris28.setMovementMethod(LinkMovementMethod.getInstance());
        scris29=(TextView) findViewById(R.id.link29);
        scris29.setMovementMethod(LinkMovementMethod.getInstance());
        scris30=(TextView) findViewById(R.id.link30);
        scris30.setMovementMethod(LinkMovementMethod.getInstance());
        scris31=(TextView) findViewById(R.id.link31);
        scris31.setMovementMethod(LinkMovementMethod.getInstance());
        scris32=(TextView) findViewById(R.id.link32);
        scris32.setMovementMethod(LinkMovementMethod.getInstance());
        scris33=(TextView) findViewById(R.id.link33);
        scris33.setMovementMethod(LinkMovementMethod.getInstance());
        scris34=(TextView) findViewById(R.id.link34);
        scris34.setMovementMethod(LinkMovementMethod.getInstance());
        scris35=(TextView) findViewById(R.id.link35);
        scris35.setMovementMethod(LinkMovementMethod.getInstance());
        scris36=(TextView) findViewById(R.id.link36);
        scris36.setMovementMethod(LinkMovementMethod.getInstance());
        scris37=(TextView) findViewById(R.id.link37);
        scris37.setMovementMethod(LinkMovementMethod.getInstance());
        scris38=(TextView) findViewById(R.id.link38);
        scris38.setMovementMethod(LinkMovementMethod.getInstance());
        scris39=(TextView) findViewById(R.id.link39);
        scris39.setMovementMethod(LinkMovementMethod.getInstance());
        scris40=(TextView) findViewById(R.id.link40);
        scris40.setMovementMethod(LinkMovementMethod.getInstance());
        scris41=(TextView) findViewById(R.id.link41);
        scris41.setMovementMethod(LinkMovementMethod.getInstance());
        scris42=(TextView) findViewById(R.id.link42);
        scris42.setMovementMethod(LinkMovementMethod.getInstance());
        scris43=(TextView) findViewById(R.id.link43);
        scris43.setMovementMethod(LinkMovementMethod.getInstance());
        scris44=(TextView) findViewById(R.id.link44);
        scris44.setMovementMethod(LinkMovementMethod.getInstance());
        scris45=(TextView) findViewById(R.id.link45);
        scris45.setMovementMethod(LinkMovementMethod.getInstance());
        scris46=(TextView) findViewById(R.id.link46);
        scris46.setMovementMethod(LinkMovementMethod.getInstance());
        scris47=(TextView) findViewById(R.id.link47);
        scris47.setMovementMethod(LinkMovementMethod.getInstance());
        scris48=(TextView) findViewById(R.id.link48);
        scris48.setMovementMethod(LinkMovementMethod.getInstance());
        scris49=(TextView) findViewById(R.id.link49);
        scris49.setMovementMethod(LinkMovementMethod.getInstance());
        scris50=(TextView) findViewById(R.id.link50);
        scris50.setMovementMethod(LinkMovementMethod.getInstance());
        scris51=(TextView) findViewById(R.id.link51);
        scris51.setMovementMethod(LinkMovementMethod.getInstance());
        scris52=(TextView) findViewById(R.id.link52);
        scris52.setMovementMethod(LinkMovementMethod.getInstance());
        scris53=(TextView) findViewById(R.id.link53);
        scris53.setMovementMethod(LinkMovementMethod.getInstance());
        scris54=(TextView) findViewById(R.id.link54);
        scris54.setMovementMethod(LinkMovementMethod.getInstance());
        scris55=(TextView) findViewById(R.id.link55);
        scris55.setMovementMethod(LinkMovementMethod.getInstance());
        scris56=(TextView) findViewById(R.id.link56);
        scris56.setMovementMethod(LinkMovementMethod.getInstance());
        scris57=(TextView) findViewById(R.id.link57);
        scris57.setMovementMethod(LinkMovementMethod.getInstance());
        scris58=(TextView) findViewById(R.id.link58);
        scris58.setMovementMethod(LinkMovementMethod.getInstance());
        scris59=(TextView) findViewById(R.id.link59);
        scris59.setMovementMethod(LinkMovementMethod.getInstance());
        scris60=(TextView) findViewById(R.id.link60);
        scris60.setMovementMethod(LinkMovementMethod.getInstance());
        scris61=(TextView) findViewById(R.id.link61);
        scris61.setMovementMethod(LinkMovementMethod.getInstance());
        scris62=(TextView) findViewById(R.id.link62);
        scris62.setMovementMethod(LinkMovementMethod.getInstance());
        scris63=(TextView) findViewById(R.id.link63);
        scris63.setMovementMethod(LinkMovementMethod.getInstance());
        scris64=(TextView) findViewById(R.id.link64);
        scris64.setMovementMethod(LinkMovementMethod.getInstance());
        scris65=(TextView) findViewById(R.id.link65);
        scris65.setMovementMethod(LinkMovementMethod.getInstance());
        scris66=(TextView) findViewById(R.id.link66);
        scris66.setMovementMethod(LinkMovementMethod.getInstance());
        scris67=(TextView) findViewById(R.id.link67);
        scris67.setMovementMethod(LinkMovementMethod.getInstance());
        scris68=(TextView) findViewById(R.id.link68);
        scris68.setMovementMethod(LinkMovementMethod.getInstance());
        scris69=(TextView) findViewById(R.id.link69);
        scris69.setMovementMethod(LinkMovementMethod.getInstance());
        scris70=(TextView) findViewById(R.id.link70);
        scris70.setMovementMethod(LinkMovementMethod.getInstance());
        scris71=(TextView) findViewById(R.id.link71);
        scris71.setMovementMethod(LinkMovementMethod.getInstance());
        scris72=(TextView) findViewById(R.id.link72);
        scris72.setMovementMethod(LinkMovementMethod.getInstance());
        scris73=(TextView) findViewById(R.id.link73);
        scris73.setMovementMethod(LinkMovementMethod.getInstance());
        scris74=(TextView) findViewById(R.id.link74);
        scris74.setMovementMethod(LinkMovementMethod.getInstance());
        scris75=(TextView) findViewById(R.id.link75);
        scris75.setMovementMethod(LinkMovementMethod.getInstance());
        scris76=(TextView) findViewById(R.id.link76);
        scris76.setMovementMethod(LinkMovementMethod.getInstance());
        scris77=(TextView) findViewById(R.id.link77);
        scris77.setMovementMethod(LinkMovementMethod.getInstance());
        scris78=(TextView) findViewById(R.id.link78);
        scris78.setMovementMethod(LinkMovementMethod.getInstance());
        scris79=(TextView) findViewById(R.id.link79);
        scris79.setMovementMethod(LinkMovementMethod.getInstance());
        scris80=(TextView) findViewById(R.id.link80);
        scris80.setMovementMethod(LinkMovementMethod.getInstance());
        scris81=(TextView) findViewById(R.id.link81);
        scris81.setMovementMethod(LinkMovementMethod.getInstance());
        scris82=(TextView) findViewById(R.id.link82);
        scris82.setMovementMethod(LinkMovementMethod.getInstance());
        scris83=(TextView) findViewById(R.id.link83);
        scris83.setMovementMethod(LinkMovementMethod.getInstance());
        scris84=(TextView) findViewById(R.id.link84);
        scris84.setMovementMethod(LinkMovementMethod.getInstance());
        scris85=(TextView) findViewById(R.id.link85);
        scris85.setMovementMethod(LinkMovementMethod.getInstance());
        scris86=(TextView) findViewById(R.id.link86);
        scris86.setMovementMethod(LinkMovementMethod.getInstance());
        scris87=(TextView) findViewById(R.id.link87);
        scris87.setMovementMethod(LinkMovementMethod.getInstance());
        scris88=(TextView) findViewById(R.id.link88);
        scris88.setMovementMethod(LinkMovementMethod.getInstance());
        scris89=(TextView) findViewById(R.id.link89);
        scris89.setMovementMethod(LinkMovementMethod.getInstance());
    }
}